# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign_enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_added', models.DateTimeField(blank=True, null=True)),
                ('Campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Lead')),
            ],
        ),
    ]
