# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_campaign_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='lead',
        ),
    ]
