# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='%Y/%m/%d'),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together=set([('name', 'email', 'phone_number')]),
        ),
    ]
