# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20171116_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_added', models.DateTimeField(blank=True, null=True)),
                ('text', models.CharField(max_length=100)),
                ('campaign_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Campaign_enrollment')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='comment',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Lead'),
        ),
    ]
