# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20171210_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='lead',
        ),
    ]
