# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20171210_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign_enrollment',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='campaign_enrollment',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
