# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20171211_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contacted_today',
            field=models.BooleanField(default=False),
        ),
    ]
