# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_lead_contacted_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contacted_today',
            field=models.NullBooleanField(default=False),
        ),
    ]
