# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20171211_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='contacted_today',
        ),
        migrations.AddField(
            model_name='lead',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
