# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 20:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20171211_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1999, 1, 1, 0, 0), null=True),
        ),
    ]
